version: '3.8'

services:
  # BACKEND VIDA NOVA
  api:
    build: .
    container_name: vidanova_api
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    networks:
      - vidanova_net
    depends_on:
      - db

  # BASE DE DATOS LOCAL (Auxiliar)
  db:
    image: postgres:15-alpine
    container_name: vidanova_db_local
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-vidanova_db}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vidanova_net

networks:
  vidanova_net:
    driver: bridge

volumes:
  pgdata: