version: '3.8'

services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: vidanova_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin  # Debe coincidir con tu .env (para desarrollo)
      POSTGRES_DB: vidanova_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Opcional: Interfaz web para ver la BD (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: vidanova_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@vidanova.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: